feat: #2 Added a test to reject invalid inputs

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -16,7 +16,15 @@ runs:
       shell: bash
       run: |
         printf "pathname=%s\n" $(git config -f .gitmodules --get 'submodule.${{ inputs.name }}.path') >> $GITHUB_OUTPUT
+    - name: Rejects invalid name
+      if: ${{ steps.locate-tree.outputs.pathname == '' }}
+      shell: bash
+      run: |
+        echo "::error line=22::${{ format('the name {0} is not defined in the HEAD.', inputs.name) }}"
+        exit 1
     - id: "tree-fields"
+      if: ${{ success() }}
+      name: Describes the the submodule ref
       shell: bash
       run: |
         git ls-tree --format 'path=%(path)' HEAD "${{ steps.locate-tree.outputs.pathname }}" >> $GITHUB_OUTPUT
